// +-- VENDORED COPY - DO NOT EDIT ------------
// | source : ~/.agents/lib/report_chrome.mjs
// | sha256 : 2500ece6f64b619f701e9f9e061a2677ae0e1af78394fad2bbb013c61c6b08a9
// | sync   : node ~/.agents/lib/sync_report_chrome.mjs
// | Edit the canonical source above, then re-run sync. Edits here are lost.
// +----------------------------------------------------------
// Shared HTML report chrome — CANONICAL source of truth for the pieces that
// must stay identical across the ~/.agents report generators.
//
// This file is the source. Consumers carry a VENDORED copy next to their own
// script (so each skill stays self-contained / portable) generated by:
//     node ~/.agents/lib/sync_report_chrome.mjs          # propagate edits
//     node ~/.agents/lib/sync_report_chrome.mjs --check   # detect drift (CI/lint)
// Edit HERE only; never edit a vendored copy. The sync manifest (which dirs get
// a copy) lives in the sync script, not here — the dependency points one way
// (consumers -> canonical).
//
// Scope = the drift-prone *mechanism*: the theme-toggle CSS, the `.kicker.prompt`
// banner, and the "Go to section" fan-out nav (CSS + runtime + markup builder).
//
// Deliberately NOT here (stays per-generator): the colour palette (each report
// is accent-tinted; shared rules reference var(--ac)), the theme bootstrap
// script/button, and the per-skill nav *scanner* (each builds its own `items`
// list, then calls jumpNavHtml(items) so only the markup is shared).
//
// Import (every consumer, from the vendored sibling copy):
//     import { CHROME_CSS, JUMP_JS, jumpNavHtml } from "./report_chrome.mjs";

// --- CSS ---------------------------------------------------------------------
const THEME_TGL_CSS = `.theme-tgl{position:fixed;top:14px;right:16px;z-index:50;font-family:var(--mono);font-size:11px;letter-spacing:.08em;text-transform:uppercase;cursor:pointer;background:var(--surface);color:var(--ink);border:1px solid var(--line);border-radius:999px;padding:6px 12px;box-shadow:0 2px 8px rgba(0,0,0,.18)}
.theme-tgl:hover{border-color:var(--ink-faint)}`;

const KICKER_CSS = `.kicker.prompt{display:flex;align-items:center;gap:0;color:var(--ac);letter-spacing:.04em;text-transform:none;font-size:13px;font-weight:600;margin:0 0 14px}
.kicker.prompt .cur{display:inline-block;width:8px;height:14px;background:var(--ac);margin-left:7px;animation:blink 1.1s steps(1) infinite}
@keyframes blink{0%,50%{opacity:1}50.01%,100%{opacity:0}}
@media (prefers-reduced-motion:reduce){.kicker.prompt .cur{animation:none;opacity:.9}}`;

// Chrome is MUTED by design: buttons use a pastel tint of the accent
// (color-mix ~12%, ink text), reserving the full accent for hover/focus/active.
// Accent = data/severity, NOT chrome — a solid-accent fill reads as too loud.
const JUMP_NAV_CSS = `.jump-nav{position:fixed;bottom:1.4rem;right:1.4rem;z-index:50;font-family:var(--mono)}
.jump-btn{display:inline-flex;align-items:center;gap:7px;background:color-mix(in srgb,var(--ac) 12%,var(--surface));color:var(--ink);border:1px solid color-mix(in srgb,var(--ac) 30%,var(--line));border-radius:999px;padding:.55rem 1.1rem;font-family:var(--mono);font-size:.78rem;font-weight:600;letter-spacing:.04em;cursor:pointer;box-shadow:0 2px 10px rgba(0,0,0,.14)}
.jump-btn:hover{background:color-mix(in srgb,var(--ac) 20%,var(--surface));border-color:color-mix(in srgb,var(--ac) 45%,var(--line))}
.jump-btn:focus-visible{outline:2px solid var(--ac);outline-offset:2px}
.jump-btn .caret{font-size:.7rem;opacity:.85;transition:transform .18s}
.jump-nav:hover .jump-btn .caret,.jump-nav.is-open .jump-btn .caret,.jump-nav:focus-within .jump-btn .caret{transform:rotate(180deg)}
.jump-menu{position:absolute;right:0;bottom:calc(100% + 8px);min-width:240px;max-width:60vw;list-style:none;margin:0;padding:6px;background:var(--surface);border:1px solid var(--line);border-radius:10px;box-shadow:0 8px 28px rgba(0,0,0,.22);opacity:0;transform:translateY(8px) scale(.98);pointer-events:none;transition:opacity .16s,transform .16s}
.jump-nav:hover .jump-menu,.jump-nav.is-open .jump-menu,.jump-nav:focus-within .jump-menu{opacity:1;transform:none;pointer-events:auto}
.jump-menu li{opacity:0;transform:translateY(6px);transition:opacity .14s,transform .14s}
.jump-nav:hover .jump-menu li,.jump-nav.is-open .jump-menu li,.jump-nav:focus-within .jump-menu li{opacity:1;transform:none}
.jump-menu li:nth-child(1){transition-delay:0ms}
.jump-menu li:nth-child(2){transition-delay:25ms}
.jump-menu li:nth-child(3){transition-delay:40ms}
.jump-menu li:nth-child(4){transition-delay:55ms}
.jump-menu li:nth-child(5){transition-delay:70ms}
.jump-menu li:nth-child(6){transition-delay:85ms}
.jump-menu li:nth-child(7){transition-delay:100ms}
.jump-menu li:nth-child(8){transition-delay:115ms}
.jump-menu li:nth-child(9){transition-delay:130ms}
.jump-menu li:nth-child(10){transition-delay:145ms}
.jump-menu li:nth-child(11){transition-delay:160ms}
.jump-menu li:nth-child(12){transition-delay:175ms}
.jump-menu a{display:block;padding:8px 12px;color:var(--ink);text-decoration:none;font-size:12px;border-radius:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.jump-menu a:hover,.jump-menu a:focus-visible{background:var(--surface-2);color:var(--ac);outline:none}
@media (prefers-reduced-motion:reduce){.jump-menu,.jump-menu li,.jump-btn .caret{transition:none;transform:none}}`;

// All shared chrome CSS in one string — append to each generator's own STYLE.
export const CHROME_CSS = [THEME_TGL_CSS, KICKER_CSS, JUMP_NAV_CSS].join("\n");

// --- JS ----------------------------------------------------------------------
// Jump-nav runtime: hover + :focus-within reveal, click toggles .is-open (touch),
// Esc closes, aria-expanded synced. Insert once inside the page's <script>.
export const JUMP_JS = `
(function(){
 var jn=document.getElementById('jump-nav');if(!jn)return;
 var btn=jn.querySelector('.jump-btn');
 function setOpen(o){jn.classList.toggle('is-open',o);btn.setAttribute('aria-expanded',o?'true':'false');}
 btn.addEventListener('click',function(e){e.preventDefault();setOpen(!jn.classList.contains('is-open'));});
 jn.addEventListener('mouseenter',function(){setOpen(true);});
 jn.addEventListener('mouseleave',function(){setOpen(false);});
 jn.addEventListener('focusin',function(){setOpen(true);});
 jn.addEventListener('focusout',function(e){if(!jn.contains(e.relatedTarget))setOpen(false);});
 document.addEventListener('keydown',function(e){if(e.key==='Escape'&&jn.classList.contains('is-open')){setOpen(false);btn.focus();}});
 jn.querySelectorAll('.jump-menu a').forEach(function(a){a.addEventListener('click',function(){setOpen(false);});});
})();
`;

// --- markup ------------------------------------------------------------------
// Mirror of Python html.escape(quote=True): & < > " '
const esc = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;").replace(/'/g, "&#x27;");

// Build the fixed 'Go to section' fan-out nav markup.
// items: array of [anchor_id, label] — anchor_id WITHOUT the leading '#'.
// The first item is conventionally ["top", "↑ Top"]. Returns '' if there are
// not at least 2 items (nothing to jump to).
export function jumpNavHtml(items) {
  if (items.length <= 1) return "";
  const lis = items.map(
    ([sid, label]) => `<li role="menuitem"><a href="#${esc(sid)}">${esc(label)}</a></li>`
  ).join("");
  return (
    '<nav class="jump-nav" id="jump-nav" aria-label="Jump to section">' +
    '<button class="jump-btn" type="button" aria-haspopup="menu" aria-expanded="false">' +
    'Go to section<span class="caret" aria-hidden="true">▾</span></button>' +
    `<ul class="jump-menu" role="menu">${lis}</ul></nav>`
  );
}
